-- Coin Cellar's findable items as base ingredients. The coin-cellar game's
-- cooking view (coin-cellar/src/cooking/) runs against this same project;
-- its tray serves these rows' slugs (cc_-prefixed so they can never collide
-- with this game's own catalogue). The two is_starter rows are coin-cellar's
-- START_INV (what a fresh save carries); starter_order 101+ keeps them clear
-- of the restaurant's own starter ordering.
-- Generated by coin-cellar/scripts/seed-cooking-ingredients.mjs --sql.
insert into ingredients (slug, name, emoji, category, description, is_starter, starter_order)
values
  ('cc_caveshroom', 'Cave Mushroom', '🍄', 'produce', 'a fat tan-capped mushroom foraged down in the cellar', true, 101),
  ('cc_mushroom', 'Wild Mushroom', '🍄', 'produce', 'a red-capped wild mushroom with white spots', false, null),
  ('cc_herb', 'Moon Herb', '🌿', 'produce', 'a fragrant silvery herb that glows faintly at night', false, null),
  ('cc_flower', 'Honey Blossom', '🌸', 'produce', 'a sweet meadow blossom dripping with nectar', false, null),
  ('cc_berries', 'Wild Berries', '🫐', 'produce', 'a handful of ripe wild berries', false, null),
  ('cc_nuts', 'Forest Nuts', '🌰', 'produce', 'crunchy acorn-like nuts from the meadow saplings', false, null),
  ('cc_meat', 'Roast Meat', '🍖', 'protein', 'a hearty haunch of roast meat on the bone', true, 102),
  ('cc_egg', 'Griffon Egg', '🥚', 'protein', 'a huge speckled egg laid by a griffon', false, null),
  ('cc_jelly', 'Slime Jelly', '🟢', 'protein', 'a wobbly green blob of slime, oddly edible', false, null),
  ('cc_bread', 'Honey Bread', '🍞', 'pantry', 'a golden loaf baked with honey', false, null),
  ('cc_potion', 'Red Potion', '🧪', 'pantry', 'a bubbling red healing drink', false, null),
  ('cc_crystal', 'Rock Crystal', '💎', 'spices', 'a shard of rock crystal that grinds into glittering dust', false, null),
  ('cc_star', 'Star Shard', '⭐', 'spices', 'a fallen star shard, warm to the touch', false, null),
  ('cc_rathide', 'Rat Hide', '🐀', 'other', 'a rolled-up rat pelt cinched with cord', false, null),
  ('cc_gem', 'Dawn Gem', '💠', 'other', 'a pale blue gem that catches the dawn', false, null),
  ('cc_fang', 'Dragon Fang', '🦷', 'other', 'a curved ivory fang from a dragon', false, null),
  ('cc_crown', 'Lost Crown', '👑', 'other', 'a lost golden crown, five points', false, null),
  ('cc_key', 'Brass Key', '🗝️', 'other', 'a heavy brass key to nobody-knows-what', false, null),
  ('cc_bomb', 'Blast Bomb', '💣', 'other', 'a round black bomb with a short fuse', false, null),
  ('cc_lantern', 'Wisp Lantern', '🏮', 'other', 'a lantern with a wisp trapped inside', false, null),
  ('cc_ring', 'Copper Ring', '💍', 'other', 'a plain ring of polished copper', false, null),
  ('cc_amulet', 'Silver Amulet', '📿', 'other', 'a silver amulet on a fine chain', false, null),
  ('cc_bell', 'Gold Bell', '🔔', 'other', 'a small bell cast in solid gold', false, null),
  ('cc_feather', 'Phoenix Feather', '🪶', 'other', 'a red feather that is always warm', false, null),
  ('cc_hourglass', 'Chrono Hourglass', '⏳', 'other', 'an hourglass whose sand falls slowly', false, null),
  ('cc_tome', 'Spell Tome', '📕', 'other', 'a heavy spellbook humming with magic', false, null),
  ('cc_wsword', 'Pine Sword', '🗡️', 'other', 'a sword carved from pine wood', false, null),
  ('cc_dagger', 'Fang Dagger', '🗡️', 'other', 'a quick little dagger with a fang blade', false, null),
  ('cc_ssword', 'Steel Sword', '⚔️', 'other', 'a long sword of polished steel', false, null),
  ('cc_shield', 'Kite Shield', '🛡️', 'other', 'a kite shield with a gold boss', false, null),
  ('cc_bow', 'Hunter''s Bow', '🏹', 'other', 'a hunter''s bow of springy wood', false, null),
  ('cc_staff', 'Oak Staff', '🪄', 'other', 'an oak staff topped with a blue stone', false, null),
  ('cc_armor', 'Steel Chestplate', '🦺', 'other', 'a steel chestplate, dungeon-dented', false, null),
  ('cc_boots', 'Swift Boots', '🥾', 'other', 'a pair of swift leather boots', false, null)
on conflict (slug) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  category = excluded.category,
  description = excluded.description,
  is_starter = excluded.is_starter,
  starter_order = excluded.starter_order;
